# Generated by Django 4.2.5 on 2023-10-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HW18', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
